
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true,
  skip-cleanup : true
  keep-history: true
  github-token: $git-hub
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: deploy